global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'python-monitoring'
    static_configs:
      - targets: ['localhost:5000']
